### ISSUE TITLE
WARN RESTFilter Error in REST API: EofException

### ISSUE THREAD

**Issue by ypopovych** [tsquillario/Jamstash#108]
I have a problem with playing files in HTML5 player. When playing transcoded files I get an error:
WARN RESTFilter Error in REST API: EofException
When I use flash player - all works fine.

For testing my subsonic server can be used: http://music.g.if.ua
Login/Password guest/guest
Can be tested on Fantomas band. All albums in Flac, so they will transcode to ogg or mp3

**Comment by acroyear** [comment]
SubFire at my office was starting to get this issue as well, just since the 5.2 update of my severs. The break happens at *exactly* 1:09, if it happens at all (many files play without issue, but certain directories were consistently having problems...but that became a clue...).

The problem wasn't transcoding (granted, I'm not transcoding flac files), but rather adding transcoding fixed it. I found that the combination of Chrome 41 and my work's crappy network, the break happens in playing variable bitrate mp3s, which included any purchased from bandcamp or amazon. If I turn on transcoding to get them resampled to a flat rate 128 or 160 (both tolerable on the crappy speakers I have at the office), things are fine.
