### ISSUE TITLE
Beta version playback not working

### ISSUE THREAD

**Issue by btouellette** [tsquillario/Jamstash#204]
When I use beta.jamstash.com I'm having issues where everything looks normal and there aren't any errors reported but no audio comes through when playing. I've attached an image showing the Chrome dev console where I'm playing an album but no sound is coming out of Chrome. Let me know if there is any debugging data I can provide.

Everything is working normally with the non-beta site.

![image](https://cloud.githubusercontent.com/assets/6272829/6333291/b267b472-bb40-11e4-939d-6ac7487e190e.png)

**Comment by btouellette** [comment]
Audio is working for beta.jamstash.com in incognito mode however it isn't working in normal browsing mode with all extensions disabled. (Chrome v40.0.2214.115 m)

**Comment by Hyzual** [comment]
I haven't checked anything else yet, but did you check that jamstash's
volume isnt 0 ?
You should see it in the console with Debug mode checked when you change it
with the keyboard.
The latest beta reintroduced setting the volume up and down with the keys +
/ - or _ / =. Since no volume slider is displayed, it's possible to set it
to 0 without realizing.
That would explain it working in incognito mode because it resets all
localStorage and therefore the volume setting.

That still indicates that we need to display the volume to the user somehow.

Le Mon Feb 23 2015 at 18:54:10, btouellette <notifications@github.com> a
écrit :

**Comment by btouellette** [comment]
That's it. It wasn't showing as muted but the volume was at 0. Must have hit - or = a couple times on the tab without realizing it. Maybe set mute on when the volume is 0 and reset to max when unmuted until there is a way to display the volume?
