### ISSUE TITLE
Make this error more specific: "Error when contacting the Subsonic server. The requested data was not found."

### ISSUE THREAD

**Issue by arielelkin** [tsquillario/Jamstash#234]
This error message should contain information about what caused it... I notice you could get it, for example, if the specified host doesn't exist, or if your credentials are invalid. 

The cause of an error that's reported should be as clear as possible so that the user can recover from it.

**Comment by Hyzual** [comment]
The error message is actually composed of two parts: "Error when contacting the Subsonic server." which is prefixed for all kinds of network errors and the second part which depends on what is called. In your case it seems to be the error returned by the server you're using (Ampache, I'd guess), as I can't find "The requested data was not found" anywhere in our code.

In short, this error "The requested data was not found" is specific to Ampache, Subsonic (and its forks Madsonic and Music Cabinet) return a different error ("Wrong username or password.") when the credentials are invalid. I suspect it is being thrown because of some incompatibility between Jamstash and Ampache (see my response to #233).

That said I've just noticed that submitting an invalid url causes a javascript error and nothing is actually displayed to the user. I'll open another one for clarity.
