### ISSUE TITLE
Error since 4.7.0 - Loading failed for the <script>

### ISSUE THREAD

**Issue by anayrat** [tsquillario/Jamstash#259]
Hello,
Since the 4.7.0 I have this error in js console:
```
Loading failed for the <script> with source “https://supysonic.url.com/rest/ping.view?c=Jamstash&cal…ack=angular.callbacks._j&f=jsonp&p=enc:xxxxxx&u=user”.
```
Here is the response of this url:
```
angular.callbacks._j({"subsonic-response": {"status": "ok", "version": "1.9.0"}})
```
I can't load album list, FYI I use supysonic as a client. I also use ultrasonic on my smartphone and it still work with the same server.
Thanks for your help

**Comment by pR0Ps** [comment]
You have something enabled in your browser that's blocking it (Firefox privacy protections, tracking blocker, ad blocker, etc).

Because you're using the `jsonp` protocol, Jamstash loads the data the same way as if you added a `<script>` tag. If you have 3rd party javascript disabled, the "script" (aka the returned data) will be blocked, which is what you're seeing.

Closing this as it isn't an issue with Jamstash.

**Comment by anayrat** [comment]
Thanks for your quick answer, you were right. After disabling ublock it works as expected.
