### ISSUE TITLE
Procedure described in GettingStarted wiki not working

### ISSUE THREAD

**Issue by EricBrunel** [tsquillario/Jamstash#267]
I'm trying to install Jamstash to my already existing Subsonic installation so I'm following the procedure described here:
https://github.com/tsquillario/Jamstash/wiki/Getting-Started
But this doesn't seem to work: the wiki says that I'm supposed to copy the contents of the 'dist' folder to the Subsonic installation, but there's no 'dist' folder in the Jamstash distribution. I tried to copy the 'app' subfolder, but it doesn't work either: I get a neverending spinning wheel and a lof of errors "GEThttp://localhost:4040/jamstash/bower_components/... [HTTP/1.1 404 Not Found 0ms]" in the browser console. And indeed, there's no 'bower_components' subfolder in the application folder...
Is there something I'm doing wrong here? Any help would be greatly appreciated.

**Comment by pR0Ps** [comment]
Sorry, I forgot to update that page after I changed how releases work. I've just updated it so it describes the correct manual setup process now.

Essentially, instead of using the contents of the `dist/` folder, use the contents of the release zip (found [here](https://github.com/tsquillario/Jamstash/releases/latest)) instead.
